services:
  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_DB: flightbooking_test
    ports:
      - "5433:5432"  # Use 5433 on the host to avoid conflicts
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_app:
    image: node:latest
    build:
      context: .  # Set to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Specify the Dockerfile name if needed
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://test_user:default_password@test_db:5432/flightbooking_test
      FORCE: "true"
    ports:
      - "3001:3001"
    depends_on:
      - test_db
    command: ["sh", "-c", "sleep 1 && node index.js"]  # Sleep to let the db run,the start
  
  test:
    image: cypress/included:latest
    working_dir: /e2e
    volumes:
      - .:/e2e
    depends_on:
      - test_app
    environment:
      CYPRESS_BASE_URL: http://test_app:3001
    command: ["cypress", "run"]

volumes:
  pgdata:
