name: Node.js CI

on:
  push:
    branches: [ "production" , "staging" , "feature/workflow" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose_test.yml"

    - name: Wait for app to be ready
      run: |
        for i in {1..10}; do
          curl http://test_app:3001 && break || sleep 5
        done
      
    - name: Run Cypress Tests
      run: |
        docker exec test_db-1 cypress run
